learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('learning_logs.urls')),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs"""

from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Home page
    # An empty string will mean the deafault url, 
    # but the 'Home' means you need to specify the home path    
    path('home/', views.index, name='index'),
    #the page that shows all topics
    path('topics/', views.topics, name='topics'),
    # Detail page for each topic
    path('topics/<int:topic_id>/', views.topic, name='topic'),
]

learning_logs/models.py
from unittest.util import _MAX_LENGTH
from django.db import models

# Create your models here.
class Topic(models.Model):
    """A class to define a topic"""
    text = models.CharField(max_length = 200)
    date_added = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        """Return the string of the model"""
        return self.text


class Entry(models.Model):
    """A class to describe entries"""
    topic = models.ForeignKey(Topic, on_delete = models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
 
 
    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model"""
        if len(self.text) < 50:
            return f"{self.text}"
        else:
            return f"{self.text[:50]}..."
            

learning_logs/views.py
from django.shortcuts import render
from .models import Topic

# Create your views here.
# The views modlue is responsible for what you see when you open the webpage

# this function renders whatever is in index.html 
# found in the learning_logs directory
def index(request):
    """The home page of learning logs"""
    return render(request, 'learning_logs/index.html')


# This function queries the database for topics added according
# to the dates added and the topics.html template displays that page
def topics(request):
    """The page that displays all topics"""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


# A function that queries the db using the objects.get() function
#to get the topic Id then orders it according to the most recrently
#added topic using -date_added, then renders it for use to the topic.html template
def topic(request, topic_id):
    """Show the entries associated with a selected topic"""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic, 'entries':entries}
    return render(request, 'learning_logs/topic.html', context)

learning_logs/templates/learning_logs/base.html
<p>
    <a href="{% url 'learning_logs:index' %}">Learning Log</a> -
    <a href="{% url 'learning_logs:topics' %}">Topics</a>
</p>

{% block content %}{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}


<p>
    Learning Log helps you keep track of your learning, for any topic
    you're learning about.
</p>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

<p>Topic: <b> {{ topic }} </b></p>

<p>Entries: </p>
<ul>
    {% for entry in entries %}
        <li>
            <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
            <p>{{ entry.text|linebreaks }}</p>
    {% empty %}
    <li>There are no Entries for {{topic}} yet</li>
        </li>
    {% endfor %}
</ul>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block content %}

<p>Topics</p>

<ul>
    {% for topic in topics %}
        <li>
            <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        </li>
    {% empty %}
        <li>No topics have been added yet</li>
    {% endfor %}
</ul>

{% endblock content %}